### ISSUE TITLE
Battle shows wrong armor and shields for stacks

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#100]
Dont multiply the armor and shields for stacks

![image](https://github.com/sirgwain/craig-stars/assets/170196074/a9decdbf-21ec-431c-9cd2-c1cbb09c8246)

**Comment by sirgwain** [comment]
The armor should be 45, because it's a base frigate. What should the shield be?

**Comment by sirgwain** [comment]
The code just displays the design's shield amount, not the stack shields

**Comment by ccmaster001** [comment]
You should see the stack as this is more interresting if you want show the Stack and (ship).
Also Armor and shield stack should variante with damage you got.
