### ISSUE TITLE
The old stars community wants integer coordinates ;-)

### ISSUE THREAD

**Issue by runholen** [sirgwain/craig-stars#117]
Space is big, but not so big in the original stars2 that you could not find enemy fleets by going to the exact x,y integer coordinates (eg anticipate someone trying to minesweep 1ly from your planet). 
And when travelling at warp, it should round up so that you should always be able to reach planets at 36,9 ly away at warp6, 49,9 ly away at warp7, 81,8ly away at warp9 etc, we are so used to this that it is very annoying for us when we see a planet eg 81,7ly away and we cannot just drag it to warp9 and go there in one turn ;-)
So we would really want integer coordinates that the ship snaps to each year it travels.

**Comment by sirgwain** [comment]
I believe this should be fixed by this commit: https://github.com/sirgwain/craig-stars/commit/21a03a6c65f5996a2d7437bd791e83f41893859a

the x and y coords are now rounded to the nearest integer when moving.
