### ISSUE TITLE
In the "Players" report, the number of capital ships shows zero which is not correct

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#121]
I have fleets with ships built on Battleship hulls but the report shows my capital-ship count as zero. The Ship Design command correctly reports 16 ships of that design.

**Comment by tmcmh** [comment]
I realize now that the count of capital ships may be based on whether they are carrying the heavy-duty torpedoes -- which my initial Battleship hull was not. A robo-player did have some capital ships in their player count, and I believe they are carrying that other type of torpedo. I'm 98% sure, though, that the original game made the determination based on hull type, not armament.

**Comment by sirgwain** [comment]
From the Stars! wiki, a capital ship is a ship with a power rating >= 2000: https://wiki.starsautohost.org/wiki/Score_Calculation

That's what I'm using.

**Comment by tmcmh** [comment]
Makes sense! I'll close this issue.

**Comment by tmcmh** [comment]
Makes sense! Marked as closed.
