### ISSUE TITLE
Able to go above 20% in the Race Creator

### ISSUE THREAD

**Issue by KentheDM** [sirgwain/craig-stars#135]
The Race Creator will allow me to select a growth rate over 20% and allow me to save. Growth rates over 20% cost no points.

![image](https://github.com/sirgwain/craig-stars/assets/171478837/b30cb6e3-49c4-4601-b01a-f79110ac0dff)

**Comment by sirgwain** [comment]
Whoops! had it 1 to 100% 😄 Thanks!
