### ISSUE TITLE
Original 2.60j gravity scales differently than craig-stairs

### ISSUE THREAD

**Issue by KentheDM** [sirgwain/craig-stars#137]
I don't know if this is intentional/it matters, but gravity in craig-stairs scales differently

Here is Stars 2.60j
![image](https://github.com/sirgwain/craig-stars/assets/171478837/9f15db9d-4434-4040-8866-d8b4d6cdff9c)

Here is Craig-Stairs
![image](https://github.com/sirgwain/craig-stars/assets/171478837/89795d78-38fb-4e56-a41f-3a0eef36d828)

**Comment by sirgwain** [comment]
It was an attempt to simplify the calc, since it's just for the UI, but you are the second person to bring it up, so I'll revert it to the original formula I found in the Freestars source. I'm not sure it's completely accurate, but it's much closer.
