### ISSUE TITLE
Make the concentration marker for Ironium easier to see (enhancement)

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#140]
Right now it's dark blue on black, nearly invisible. It was this way in the DOS version.

**Comment by sirgwain** [comment]
There has to be some neat css color blend way to do this, but I can't yet figure it out.

**Comment by tmcmh** [comment]
Just make them white? There's no reason (I think) for the markers to use the colors associated with the corresponding minerals, because the concentration markers don't appear anywhere else besides the planet-info window.

**Comment by sirgwain** [comment]
I tried white, but they were hard to see when in front of the bars. I opted for the darker colors with a white outline. 

<img width="383" alt="image" src="https://github.com/sirgwain/craig-stars/assets/339216/7ef749d2-ded8-4b1c-bb76-22d85a9bfb05">
<img width="406" alt="image" src="https://github.com/sirgwain/craig-stars/assets/339216/a5744da2-0d30-45b7-b528-f4b0ad08b307">
