### ISSUE TITLE
Max and Min Terraform appear to be swapped

### ISSUE THREAD

**Issue by KentheDM** [sirgwain/craig-stars#143]
Example: In control of Montgomery
![image](https://github.com/sirgwain/craig-stars/assets/171478837/460cd47e-d976-4e90-910d-a78b7bb7c9f5)

Montgomery is habitable, so there shouldn't be any Min Terraform, but there should be Max Terraform. The production queue shows the opposite. Min Terraform is active and Max is greyed out.
![image](https://github.com/sirgwain/craig-stars/assets/171478837/06402e6e-dcdb-4190-8c59-15685e9baca9)

Here is the Stars! Original Helpfile, if it helps.
![image](https://github.com/sirgwain/craig-stars/assets/171478837/c71095b1-dd8d-4ded-a591-ac83edd87eef)

**Comment by sirgwain** [comment]
Auto min/max terraform should always be available (and they are in regular Stars!). If a comet hits your planet, it's fine to have auto terraform orders to restore the hab, even if it was perfect before.

**Comment by KentheDM** [comment]
Sure! I have no problem with them being available. My point is that Min Terraform in the queue is acting as if it were Max Terraform. When you have Min Terraform in the queue it should only terraform up to the point of making the planet have a positive value. However, in the example posted, the planet is well within habitable range, but the min terraform is still triggering the terraform.

For a habitable (positive value) planet with terraforming available, max terraform should trigger terraform, not min.

Does that make sense?

**Comment by sirgwain** [comment]
oh I see, it's grayed out for Max but available for min, and it should be the opposite. I'm pretty sure the server side works, I bet this is a client production estimator bug.

**Comment by KentheDM** [comment]
I don't have enough coding experience to know, but the _behavior_ I am getting from all my settled habitable planets is that they are all producing terraforming from min terraforming even though they are in the green. It's an estimator issue.

I mucked with the production queue because I am running a factoryless race, so its possible I am missing something. If you can look at games, the name of my singleplayer game "JOAT -F Test"

**Comment by sirgwain** [comment]
interestingly, OG Stars! shows the planet hab, and base hab along with a line from hab -> terraform ability. I added that in to troubleshoot.

<img width="497" alt="image" src="https://github.com/sirgwain/craig-stars/assets/339216/2d4b0fe9-f415-47c6-94a2-7b0e8082e3ba">

**Comment by sirgwain** [comment]
Should be fixed now. Check on v0.0.32
