### ISSUE TITLE
You should see needed research in Tech

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#149]
When you open the Tech over few you should not only see the Tech level needed also the Ressourses bast on your techsetting should stand there. Like you see it in F4.

**Comment by Bertie690** [comment]
I think this should be fixed now…?
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/a3695fd0-5ae0-4168-a558-916cdc50f378">

**Comment by ccmaster001** [comment]
![image](https://github.com/user-attachments/assets/35cf6542-1e87-40eb-93b9-68c05a4351dd)

TechOverview F2 not research F4.

**Comment by Bertie690** [comment]
Oh wrong dialog.
I get confused between the hotkeys due to playing on mobile.
Good catch!
