### ISSUE TITLE
Player Score not showing planets

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#161]
Planets are not showed in the score.

![image](https://github.com/sirgwain/craig-stars/assets/170196074/b0a6a054-ed80-4989-9468-f83fe2c5f841)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/be9ea104-d0a8-4392-8a0a-c00cba4dab2e)

**Comment by sirgwain** [comment]
Seems fixed. In anotherr MP game I see planets
