### ISSUE TITLE
Warp calculation rounding problem

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#162]
If the game showes 81,0 lj you may not reach the planet in 1 warp 9 jump. The game seems to round the displayed nummbers but dont show it seems like 81,01 Lj.

Also in stars it always rounds down so you can fly 81,99 Lj with warp 9 in 1 year.

**Comment by sirgwain** [comment]
fixed by https://github.com/sirgwain/craig-stars/pull/188
