### ISSUE TITLE
Battle Summary Shows "NaN" for Player Fleet Results

### ISSUE THREAD

**Issue by KentheDM** [sirgwain/craig-stars#166]
I think this happened after the last update:

![image](https://github.com/sirgwain/craig-stars/assets/171478837/eda83baf-5fc5-44de-9d89-239a25ccd045)

**Comment by sirgwain** [comment]
Huh, I didn't touch that specific code. Any chance you can give me the JSON for the battles?

**Comment by KentheDM** [comment]
uh..... how would I do that?

**Comment by sirgwain** [comment]
You'd have to use the developer inspector in your browser. Don't worry about it. 

I should provide a mechanism to download it and include it in issues. That would be helpful.
