### ISSUE TITLE
Planet is still owend even if the planet is at 0 Kolonists 

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#179]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/8afc08bd-dc3f-429e-9d41-f8580c2b32e5)

I can unload colonists there but they instant dispersal

Planet seems not to be unkolonized, here a better example:

![image](https://github.com/sirgwain/craig-stars/assets/170196074/b088e622-5e0a-43fe-8067-7df47d717059)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/f5a77e61-de18-4093-8bc7-6105f969139d)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/3198ac8b-6078-4fea-8817-5c7c7a1fbdc8)

so it seems he be in different states at the same time.

**Comment by sirgwain** [comment]
This should be fixed now. We had a min colonists of 100 bug.
