### ISSUE TITLE
you normal can see the weight of the designs

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#181]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/29d8832d-707e-4c58-ba92-37660c4c2ce0)

not only fleet also the weight of the ships you can see, not the designs without scanning it.

So you can have a good guess what kind of design it is by weight.

**Comment by sirgwain** [comment]
fixed by https://github.com/sirgwain/craig-stars/pull/188

**Comment by ccmaster001** [comment]
Not fixed. Now they are sometimes there sometimes not.

**Comment by sirgwain** [comment]
It will work in future games and future design discoveries, but for current games the discovery is the same. When you discover a new design for the first time it'll record the mass.
