### ISSUE TITLE
calculation wrong score

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#183]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/a735d70f-1271-41da-a980-06bf6ad50eec)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/e24389f0-4991-41d3-81b3-84edfe03ce1f)

got it this turn ...

**Comment by sirgwain** [comment]
fixed by fixed by https://github.com/sirgwain/craig-stars/pull/188
