### ISSUE TITLE
mines not posible to build and block the produktion

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#189]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/4c12587d-15a7-4f20-9586-d335eef04c2a)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/5e53b10d-dad7-437a-b2f9-779cc43afeb4)

**Comment by sirgwain** [comment]
This should be fixed with the new estimator code.
