### ISSUE TITLE
Research calculation bug

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#191]
When you change research field the nummber for next year research goes down to 0 and stays buggy.

![image](https://github.com/sirgwain/craig-stars/assets/170196074/b369e2ca-c7cc-49e7-b05b-2d2ef3ec5c0f)

The Reseach nummber is an importent tool and have to work right

**Comment by Bertie690** [comment]
Can’t seem to reproduce this for the life of me.
IDK if the issue still remains at this point so maybe this could use some revisiting and/or some more info…

**Comment by ccmaster001** [comment]
Change the research field and it drops. Not working anymore not fixed.

**Comment by sirgwain** [comment]
It still happens, but I can't repro it either. I'm missing some step.

**Comment by Bertie690** [comment]
I did have it drop to 0 _once_ when changing the allotted research % amount, but all subsequent attempts at reproduction since then have failed. 
I might be dumb though so don't take my word for it 100%.

**Comment by Bertie690** [comment]
Ok I am 99% sure this is related to another bug where planets that are not actively contributing to research do not have their leftover resources from production added to the tally until after their production queues get updated by changing their orders.
Idk how to fix it but i guess it's progress?
