### ISSUE TITLE
Unload colonists when colonizing loses colonists

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#210]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/30cb6998-dc0d-43a5-8499-53cfb25d634f)

When you unload kolonists in the same turn you kolonize a planet they got delated.

**Comment by sirgwain** [comment]
ok, I just tested this on OG Stars!

* sent colonizer to planet
* by-hand unloaded 1kT of colonists
* set colonize order

Next turn the colonizer is scrapped and I see this message:

<img width="645" alt="image" src="https://github.com/user-attachments/assets/b2dd9c82-952d-4bce-9d38-9cd19dd86cda">
