### ISSUE TITLE
Battle - unarmed ships go to disengage

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#212]
![image](https://github.com/sirgwain/craig-stars/assets/170196074/b49815eb-5782-4127-adcc-fefc913bba3b)

unarmed ships always go to disengage as battle order , they have nothing to do in a battle.

**Comment by sirgwain** [comment]
Unarmed ships always run away. The runaway algorithm could be improved, but it's trying to find the square with least damage
