### ISSUE TITLE
Waypoint task transitions to waypoint list before task is set up

### ISSUE THREAD

**Issue by downsider** [sirgwain/craig-stars#263]
It's only a minor annoyance, but if I change a waypoint task, it immediately changes back to the waypoint list, so setting up a transfer means I have to then navigate back to the task pane to set up what needs to be transferred. 

Could we either disable that transition or have it wait till a task is fully set up please?

**Comment by sirgwain** [comment]
oh whoops. I'm reacting to the selectedWaypoint changing, but I should react to the selectedWaypointIndex changing.
