### ISSUE TITLE
Am I able to slow an Ultra Driver (warp 10) to send a mineral packet safely to a Mass Driver (warp 7)

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#267]
I don't seem to be able to slow a warp 10 driver down to send a packet safely to the lower-grade tech. I can speed a driver up, but not slow it down.

**Comment by sirgwain** [comment]
Checking the docs again, yes you should be able to. 

https://wiki.starsautohost.org/wiki/%22Mass_Packet_FAQ%22_by_Barry_Kearns_1997-02-07_v2.6b

Also, packets are supposed to decay when sent at normal speed. I think mine are decaying if you are PP. 

Thanks for the issue!
