### ISSUE TITLE
Battle Damage Calculation

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#272]
Ships only die if the damage is enouth, from one blast with beam weapons, to kill it complete ( or the remaining Armor of a damaged ship).
![image](https://github.com/sirgwain/craig-stars/assets/170196074/20da3b91-54d8-449c-be86-2fca958bc043)

2 Ship are damaged to 49% base Armore of the design is 300. So around 150 Armor is left of every ship.

![image](https://github.com/sirgwain/craig-stars/assets/170196074/41026f38-97fe-4682-be72-1bd9534c005b)

50 damage done to the ship. Lost a ship as the Stack armor comes under 300, should not be this way. Fleet damage should go up.

**Comment by sirgwain** [comment]
I believe this was more of a recording issue than an actual damage issue. I updated the token details to better report the state of a stack. Please check again.
