### ISSUE TITLE
Costcalculation of Starbases is wrong

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#279]
Starbases have to be much cheaper.

**Comment by sirgwain** [comment]
Can you give me an example of a star base build in stars vs craig-stars? The cost should just be components plus hull

**Comment by Bertie690** [comment]
From what I can tell at least, the cost calcs are incorrect for weapons/armor added onto starbases - starbases _should_ have an innate 50% discount compared to normal price (a discount not appearing to apply for craig-stars).

**Comment by sirgwain** [comment]
weapons and armor cost 50% less to mount to starbases? wow. that might explain this issue... https://github.com/sirgwain/craig-stars/issues/279

**Comment by Bertie690** [comment]
Yes - I'm 90% confident it was done to balance out starbases' high baseline hull costs & immobility. 
I need to check what parts the 50% discount specifically applies to (orbitals don't count, but IDK about electrical).

**Comment by Bertie690** [comment]
Ok after further testing, it appears that starbases get a 50% innate stackable discount on everything EXCEPT orbital devices (which makes sense since those can _only_ go on starbases). The costs appear to be tabulated as a float and then rounded up at the end.

**Comment by ccmaster001** [comment]
Stacky with ISB and the I T get a discound for gates.

**Comment by ccmaster001** [comment]
Still not works correct.

![image](https://github.com/user-attachments/assets/cb33091a-c131-4d9f-8914-674d73696894)

![image](https://github.com/user-attachments/assets/0b06303f-9475-4a7f-9adb-2bc2588edefb)

**Comment by Bertie690** [comment]
Does it actually work when you try to build the design?

**Comment by Bertie690** [comment]
That's odd - it appears the ISB discount doesn't work on docks.
🤦

**Comment by ccmaster001** [comment]
no still 100 used

Am So., 8. Sept. 2024 um 16:30 Uhr schrieb Bertie690 <
***@***.***>:
