### ISSUE TITLE
Add MT trader parts to Tech Browser 

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#285]
Being able to see the specs of the various goodies that the Mystery Trader can give you in the Tech browser would be nice. 
I'm thinking either go under a separate section ("MT Parts") or in their respective item sections. (Thinking of having a blue/cyan tagline under them mentioning their exclusivity - "This part is a remnant of mysterious technology. Maybe a certain trader offers it..."
The item descriptions could either be unlocked by default or by after receiving the corresponding part for the first time in a game.

**Comment by sirgwain** [comment]
I have an open PR for this that is taking me forever to complete because I keep fixing bugs instead. :)

It's on the list for sure.

**Comment by Bertie690** [comment]
I can help contribute stats for the items. IIRC it should be on a webpage somewhere...
(Worst comes to worst I just boot up a test save file and wait 10000 years for the MT to arrive.)
