### ISSUE TITLE
Logging in with Discord display name vs username

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#287]
When I first created an account on craig-stars, it used my alias on the Discord server (ymmot_98292). That works fine from my home computer. But when I try to log on from my laptop, it picks up my general Discord username (invariate), so I don't see the games I saved under the original account.

I'm not sure if this is an issue or not, it may be a nuance of Discord that I'm missing.

**Comment by sirgwain** [comment]
I checked the user database. `invariate` has a discord id of `76754****`  and `ymmot_98292` has a discord id of `12149*****`. 

A while ago, discord did a user update thing to remove the discriminators from usernames (https://discord.com/blog/usernames), but that doesn't seem related to this. It seems like you have two discord accounts (at least by the ID)
