### ISSUE TITLE
You should be able to set a mass-driver destination to 'None'

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#309]
No biggie: as a safety measure (so you don't shoot at a destination not appropriately equipped), you should be able to set the destination of a Mass Driver to 'None.' In legacy Stars!, this was accomplished by choosing to 'Set' the driver destination and then clicking on the home planet for that starbase, rather than another planet.

**Comment by sirgwain** [comment]
Thanks for the issue. I updated it to support removing a packet target and I also updated the cursor to the add waypoint plus sign when you're in set dest mode.
