### ISSUE TITLE
Incorrect message text...?

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#320]
<img width="375" alt="image" src="https://github.com/user-attachments/assets/70b3039a-4aeb-499f-8170-f5302e39e882">
Game make up your mind plz - is it 5% or 2.7% dieoff?

**Comment by sirgwain** [comment]
How does the original work?

**Comment by Bertie690** [comment]
I'm pretty sure the message is wrong - the die-off should by all accounts be 2.7% (-hab/10). 
It works fine for positive hab planets, just red ones where it says the wrong thing.

**Comment by sirgwain** [comment]
Ah I see, the popup text says 1.5% die off for a -15% planet, so yeah, the message is probably off. I was thinking the hab rating was based on your growth rate or something, but I guess it's simpler than all that.
