### ISSUE TITLE
IT not getting discount on stargates

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#323]
<img width="375" alt="image" src="https://github.com/user-attachments/assets/91136ca2-82be-41f1-b508-03b5e7ca1f29">
For the record, I will have to check the prices when I get home, as IIRC a non-miniaturized orbital fort + gate costs around the ballpark of 180 resources to build. (Also 50kT iron & 32kT germ IIRC)

**Comment by sirgwain** [comment]
Yes please confirm with OG Stars!. The discounts for IT + ISB don't stack.

**Comment by Bertie690** [comment]
The IT & ISB discounts do stack in OG stars. That said, it doesn't stack with the AR starbase discount. (I know this because I tested it last Tuesday out of boredom.)

For the record, I don't even have ISB for this race, so the issue isn't that the discount doesn't stack. The issue is it doesn't look like I'm getting a discount at all!

**Comment by Bertie690** [comment]
![image](https://github.com/user-attachments/assets/a7546587-fa4c-4f51-b957-59d654712be4)
Pulled up OG stars in new game without any fancy settings and yes, it appears craig-stars is overcharging me for stargates. (The 25% discount appears to be baked in to the unit price, so ISB/miniaturization would stack multiplicatively with it as well.)
