### ISSUE TITLE
New Label Type: Visual

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#352]
For all visual and UI-related bugs, issues and features.

**Comment by sirgwain** [comment]
There is a "client" label that I'm barely using because every issue involves changes to the client.

Is there something more specific about this? Typos, color, spacing? Is this for minor visual bugs?

**Comment by Bertie690** [comment]
I suppose typos (or textual errors in general) could get their own label. 
I was thinking more graphical errors/suggestions and whatnot.

**Comment by sirgwain** [comment]
Done. I changed the client label to visual to represent visual cosmetic bugs
