### ISSUE TITLE
Planet scan after battle

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#358]
You should see the fleet killed your world.

![image](https://github.com/user-attachments/assets/93be8c35-7b57-4fc1-9898-e8c8cf2b5a65)

**Comment by ccmaster001** [comment]
And you should see a fleet bombing you at the moment.
![image](https://github.com/user-attachments/assets/e2e1a799-e458-40a8-8eae-a9411b3f11b5)

**Comment by sirgwain** [comment]
This should be partially done. If a fleet is above any planet you own, it will be scanned.

**Comment by sirgwain** [comment]
I still need to add scanning anytime a fleet bombs or invades your planet so you know about it even if all your people are destroyed. Those colonists sure are good at pressing that send button right as the last bomb drops.
