### ISSUE TITLE
Regular/LBU bombs have 10x lower destruction counts than normal 

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#368]
All the LBU and standard bombs have their installation destroy counts cut in 10 from their amounts in base Stars!. 
(So the cherry bomb destroys 1 installation instead of 10, etc etc.)
This doesn't apply to either of the 2 MT bomb items (which work normally).

**Comment by sirgwain** [comment]
Huh, I'm not sure why I was treating the StructureKillRate as a fraction (.2) instead of a whole number (2)
