### ISSUE TITLE
Checking fleets

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#372]
![image](https://github.com/user-attachments/assets/65aae730-7b59-4612-85ea-ff899baca945)

when you check the fleets there give all Informations to the player , Weight Movmentspeed etc. so we have not to look somewhere else.

**Comment by ccmaster001** [comment]
ok seems to where version bug again

**Comment by sirgwain** [comment]
What was the issue? Design popup not working?
