### ISSUE TITLE
Warp speed set

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#388]
If a fllet target a Planet with Station it should automatic set warp to reach it as fast as it can. will be refilled there anyway.

**Comment by Bertie690** [comment]
Unfortunately, doing this requires me to change the code used to find the fastest useful warp speed (if I can find out where it even is).
I might get around to doing it eventually...😅

**Comment by Bertie690** [comment]
This was added recently, so we can probably close this.
