### ISSUE TITLE
ShipDesign range estimate doesn't account for multiple engines

### ISSUE THREAD

**Issue by sirgwain** [sirgwain/craig-stars#461]
fuel cost doesn't account for multiple engines at all?

**Comment by qop08** [comment]
In OG stars fuel usage is unaffected by the number of engines. I tested this with a privateer and galleon travelling the same distance at the same warp. The ratio of fuel usage was the same as the mass ratio. The extra engines on the galleon did not have any effect.
However, fuel generation is based on the number of engines and ignores the mass. (Also tested in OG stars)

**Comment by sirgwain** [comment]
Oh good! I guess I don't need to fix this. Thanks for checking!
