### ISSUE TITLE
Planets without "Contributes to Research" checkbox enabled do not show leftover production resources in research dialog or planet modal tooltip until their production queue gets updated

### ISSUE THREAD

**Issue by Bertie690** [sirgwain/craig-stars#465]
IDK whether the extra resources actually go towards research or not (I'd _presume_ they do), but either way fun bug.

**Comment by Bertie690** [comment]
Images attached for reference:
![image](https://github.com/user-attachments/assets/a16cd4e9-b5df-499d-af71-28a273cc0a9c)
![image](https://github.com/user-attachments/assets/652fb3db-a207-49a9-8c36-5e77652b2776)
![image](https://github.com/user-attachments/assets/83d337b4-a8a3-40eb-8c4f-3205ddf5b8c3)

**Comment by sirgwain** [comment]
I need to assume all resources are "leftover" if a planet has no production queue

**Comment by Bertie690** [comment]
![image](https://github.com/user-attachments/assets/6d725517-eddb-47c5-9cba-3b7328697d3b)
![image](https://github.com/user-attachments/assets/2e84e0f6-e4ab-48e5-a771-6b8abbc51208)
@sirgwain sorry to be a bother but this still happens with finished autobuild orders. Refreshing the queue does seem to update results.

**Comment by sirgwain** [comment]
Next round. We need a turn gen to fix each game
