### ISSUE TITLE
Galleon has incorrect slots

### ISSUE THREAD

**Issue by sirgwain** [sirgwain/craig-stars#529]
![image](https://github.com/user-attachments/assets/b754ce57-4aef-4d20-bedb-97ca72e56ee9)

Should be Elec/Mech not general for lower front slot

**Comment by Bertie690** [comment]
Actually, this bug is properly implemented in game (I checked it myself and only elec/mech items were placable in the slot) - it just has the wrong text in the ship designer for whatever reason.

**Comment by Bertie690** [comment]
Requesting downgrade of bug priority level to "visual P2"
