### ISSUE TITLE
"Waiting or players to play" and "Internal Server Error" on 1 game, not on others

### ISSUE THREAD

**Issue by tmcmh** [sirgwain/craig-stars#576]
When I try to submit a turn for this game:

https://craig-stars.net/games/349

I see a message "Waiting for players to play" though the three AI players are showing as having submitted their moves. "Unsubmit" doesn't seem to do anything, and "Force Generate" returns the server error.

Other games seem to be working fine, it's just #349.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/65c89295-c1d5-4f1b-a8b2-d589c48e497a">

**Comment by sirgwain** [comment]
I recently added some logging around scrapping and it was crashing if something was scrapped away from a planet. Please try force generating the turn when the next version is deployed.

**Comment by tmcmh** [comment]
This seems to have worked, I'm playing to see if it stays stable. I did in fact scrap a ship in space just before the freeze-up.
