### ISSUE TITLE
Wrong Cost for all Spacestations

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#65]
All cost for the space stations are wrong/old.

**Comment by sirgwain** [comment]
Is this still true with the latest commit? I fixed the 100 -> 80 resource cost for the Space Dock here: 

https://github.com/sirgwain/craig-stars/commit/10aeefed43ba983633f27dee4b3478c7849bad6f#diff-a1c5915ee74a72be0065ea3275d6e12a9ede630f4168ac6e63a7edb088eb68ddL2466

**Comment by ccmaster001** [comment]
was my test post yes fixed at least doch rest i have not looked
