### ISSUE TITLE
You can not intercept Packets or fleets

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#66]
Movement only possible between planets.

**Comment by sirgwain** [comment]
Do you have an example of this? I know you can intercept fleets because it's been tested a lot. I haven't tried to target packets though.

**Comment by ccmaster001** [comment]
Can't set my WP to a fleet fly in space. Engine only allowed target planet where i could change to a fleet. But i see no possibility to target a space flying fleet.

**Comment by sirgwain** [comment]
Oh darn, I broke this while improving the automatic stargate warp speed settings on adding a waypoint.
