### ISSUE TITLE
CC Slots are wrong

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#67]
![Unbenannt](https://github.com/sirgwain/craig-stars/assets/170196074/ef2d1820-1626-42c7-b17e-9cdda46a5b87)

![image](https://github.com/sirgwain/craig-stars/assets/170196074/e59fbbd2-eacd-4881-b0c4-11fa0ca3afa6)

**Comment by sirgwain** [comment]
looks ok? https://craig-stars.net/techs/cruiser

what am I missing? Which slot is incorrect?

**Comment by ccmaster001** [comment]
you have scanner there where shield has to be. next to engine slot
