### ISSUE TITLE
Ship movment base warp set

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#90]
the warp of ships is set to best fule use or something, noone wants that and you have to change it every time.

Can you set it to best warp without danger to reach the planet as fast as possible ?

Distanz 50 lj should be automatic warp 8 and so on.

![image](https://github.com/sirgwain/craig-stars/assets/170196074/6bd5f6c3-6f2e-4e06-ab18-c78f4c749f61)

**Comment by sirgwain** [comment]
The speed calculations for colonizers choose the fastest warp without running out of speed.
For other ships, it starts at the engine's Ideal Warp, and then goes slower as long as the fleet arrives in the same time. I.e. if it takes 4 years at warp 6, 4 years at warp 5, and 5 years at warp 4, it will go warp 5.

I believe this is the same as the original Stars!

**Comment by ccmaster001** [comment]
Yes but also in the original it is bad, so it would be an enchantment to save players to set up the warp. you want to fly 99% of the time as fast as needed to reach a planet.

**Comment by sirgwain** [comment]
Are there scenarios where you wouldn't want this?

**Comment by ccmaster001** [comment]
Yes if you need the fule and want to fly some extra Lj. But then you can still change it with hand.

**Comment by sirgwain** [comment]
There are now hot keys to move at max warp vs ideal engine speed warp. 

Holding control (command on Mac) will go at max warp. Much like adding 100 items in the production queue vs adding only 10 with shift.
