### ISSUE TITLE
Wrong armor for the FF

### ISSUE THREAD

**Issue by ccmaster001** [sirgwain/craig-stars#99]
Armor is 45

![image](https://github.com/sirgwain/craig-stars/assets/170196074/b2e74ecc-d52a-44e3-a279-029d1f5462e5)

**Comment by sirgwain** [comment]
weird, it looks correct on my end.
<img width="938" alt="image" src="https://github.com/sirgwain/craig-stars/assets/339216/2dfe56b3-ee94-41e0-8408-25eb55f692f2">

**Comment by sirgwain** [comment]
Do you have regenerating shields? that cuts your armor in half.

Does that not impact the base armor? (makes sense I suppose)

**Comment by sirgwain** [comment]
ah I see, RS only impacts added armor, not base armor. fixing, thanks!
